export type ArtCardDomElements = {
  artCardTitle: HTMLElement;
  artCardDescription: HTMLElement;
  artCardImage: HTMLImageElement;
  artCardSynoptic: HTMLElement;
  artCardAudioToggle: HTMLButtonElement;
  artCardAudio: HTMLAudioElement;
};

export type ArtEditDomElements = {
  artEditPanel: HTMLElement;
  artEditId: HTMLInputElement;
  artEditTitle: HTMLInputElement;
  artEditDescription: HTMLTextAreaElement;
  artEditRoom: HTMLSelectElement;
  artEditRoomWidthCm: HTMLInputElement;
  artEditRoomDepthCm: HTMLInputElement;
  artEditRoomHeightCm: HTMLInputElement;
  artEditWall: HTMLSelectElement;
  artEditOffsetCm: HTMLInputElement;
  artEditWidthCm: HTMLInputElement;
  artEditHeightCm: HTMLInputElement;
  artEditFrameBorderCm: HTMLInputElement;
  artEditFrameColor: HTMLInputElement;
  artEditCenterYCm: HTMLInputElement;
  artEditImageUrl: HTMLInputElement;
  artEditAudioStatus: HTMLElement;
  artEditAudioSelect: HTMLSelectElement;
  artEditAudioWaveform: HTMLCanvasElement;
  artEditAudioStartSec: HTMLInputElement;
  artEditAudioEndSec: HTMLInputElement;
  artEditAudioAutoplay: HTMLInputElement;
  artEditAudioToggle: HTMLButtonElement;
  artEditAudioPause: HTMLButtonElement;
  artEditAudioStop: HTMLButtonElement;
  artEditAudioUpload: HTMLButtonElement;
  artEditAudioClear: HTMLButtonElement;
  artEditAudioRecord: HTMLButtonElement;
  artEditAudioRecordStop: HTMLButtonElement;
  artEditAudioFile: HTMLInputElement;
  artEditAudioDropZone: HTMLElement;
  artEditSynopsisList: HTMLElement;
  artEditDelete: HTMLButtonElement;
  artEditMoveLeft: HTMLButtonElement;
  artEditMoveRight: HTMLButtonElement;
  artEditMoveUp: HTMLButtonElement;
  artEditMoveDown: HTMLButtonElement;
};
